"""YAML pull/push for course content.

pull  — serialise live Moodle state to a YAML string
diff  — compare a parsed YAML dict to live state, return a list of Change objects
push  — execute a list of Change objects against the Moodle API
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable

import yaml

from moodlectl.types import Cmid, CourseId, MoodleClientProtocol, SectionId

# Progress callback type: (current, total, description) -> None
ProgressCb = Callable[[int, int, str], None]


# ---------------------------------------------------------------------------
# Serialisation helpers
# ---------------------------------------------------------------------------

_HEADER = """\
# Generated by moodlectl content pull
# Editable:   course settings, section/module name, visible, module settings
# Read-only:  course_id, section id/number, module cmid/type/description/due_date
# To reorder: change the order of modules or sections — push detects and applies moves
# To add/del: use Moodle web UI — push warns but never auto-deletes
# Dates use 'YYYY-MM-DD HH:MM' format
"""


def pull(
    client: MoodleClientProtocol,
    course_id: CourseId,
    progress: ProgressCb | None = None,
) -> str:
    """Return a YAML string representing the current course content state."""
    from moodlectl.client.api import _build_module_settings  # type: ignore[attr-defined]

    # First pass: structure only (fast — 1 HTTP request).
    sections = client.get_course_sections(course_id)  # type: ignore[call-arg]

    all_modules = [(s, m) for s in sections for m in s["modules"]]
    total = len(all_modules)

    # Course-level settings
    from moodlectl.features.courses import get_course_settings
    raw_course_settings = get_course_settings(client, course_id)  # type: ignore[arg-type]
    course_settings = {k: v for k, v in raw_course_settings.items() if v not in ("", [], 0, 0.0, None)}

    # Due-date map (best-effort)
    due_by_cmid: dict[int, str] = {}
    try:
        for a in client.get_course_assignments(course_id):
            due_by_cmid[int(a["cmid"])] = a["due_text"]
    except Exception:
        pass

    # Second pass: fetch settings per module so we can report progress.
    settings_by_cmid: dict[int, dict[str, Any]] = {}
    for idx, (_, m) in enumerate(all_modules, 1):
        cmid = int(m["cmid"])
        modname = m["modname"]
        if progress:
            progress(idx, total, m["name"])
        try:
            form = client.get_module_form(m["cmid"])  # type: ignore[attr-defined]
            settings_by_cmid[cmid] = _build_module_settings(form, modname)
        except Exception:
            pass

    data: dict[str, Any] = {
        "course_id": int(course_id),
        "course": course_settings,
        "sections": [],
    }

    for s in sections:
        sec_dict: dict[str, Any] = {
            "id": int(s["id"]),
            "number": s["number"],
            "name": s["name"],
            "visible": s["visible"],
        }
        if s["summary"]:
            sec_dict["summary"] = s["summary"]

        mods = []
        for m in s["modules"]:
            cmid = int(m["cmid"])
            mod_dict: dict[str, Any] = {
                "cmid": cmid,
                "type": m["modname"],
                "name": m["name"],
                "visible": m["visible"],
            }
            if m["description"]:
                mod_dict["description"] = m["description"]
            due = due_by_cmid.get(cmid, "")
            if due:
                mod_dict["due_date"] = due
            if settings_by_cmid.get(cmid):
                mod_dict["settings"] = settings_by_cmid[cmid]
            mods.append(mod_dict)

        sec_dict["modules"] = mods
        data["sections"].append(sec_dict)

    return _HEADER + yaml.dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False)


# ---------------------------------------------------------------------------
# Diff engine
# ---------------------------------------------------------------------------

@dataclass
class Change:
    kind: str          # RENAME_MODULE|RENAME_SECTION|HIDE_MODULE|SHOW_MODULE|HIDE_SECTION|SHOW_SECTION|MOVE_MODULE|MOVE_SECTION|UPDATE_MODULE|UPDATE_COURSE|CREATE_MODULE
    label: str         # human-readable description for the summary table
    cmid: Cmid | None = None
    section_id: SectionId | None = None
    value: str | bool | dict[str, Any] | None = None
    target_cmid: int = 0        # MOVE_MODULE only: 0=end, >0=place before this cmid
    course_id: CourseId | None = None  # MOVE_MODULE|CREATE_MODULE
    modname: str = ""           # UPDATE_MODULE|CREATE_MODULE: module type (assign/quiz/…)
    section_num: int | None = None     # CREATE_MODULE only: 0-indexed section number
    new_name: str = ""                 # CREATE_MODULE only
    new_settings: dict[str, Any] | None = None  # CREATE_MODULE only


def _compute_section_moves(desired: list[SectionId], current: list[SectionId]) -> list[tuple[SectionId, SectionId]]:
    """Return (section_id, place_before_section_id) moves to reorder sections.

    Processes right-to-left, skipping the last element — it falls into place
    as others move around it. Unlike module moves, there is no valid "end"
    sentinel for the section_move API, so this never produces a target of 0.
    """
    if desired == current:
        return []

    moves: list[tuple[SectionId, SectionId]] = []
    simulated = list(current)

    for i in range(len(desired) - 2, -1, -1):  # stop before last element
        sec_id = desired[i]
        if simulated.index(sec_id) == i:
            continue

        before = desired[i + 1]
        moves.append((sec_id, before))

        simulated.remove(sec_id)
        insert_pos = simulated.index(before)
        simulated.insert(insert_pos, sec_id)

    return moves


def _compute_moves(desired: list[Cmid], current: list[Cmid]) -> list[tuple[Cmid, int]]:
    """Return the minimal (cmid, target_cmid) moves to transform current into desired order.

    Processes right-to-left: each module is placed before its successor in the
    desired order (target_cmid=0 means append to end). Skips modules already in
    the correct position relative to what's been placed so far.
    """
    if desired == current:
        return []

    moves: list[tuple[Cmid, int]] = []
    simulated = list(current)

    for i in range(len(desired) - 1, -1, -1):
        cmid = desired[i]
        if simulated.index(cmid) == i:
            continue  # already in the right slot

        target_cmid = int(desired[i + 1]) if i < len(desired) - 1 else 0
        moves.append((cmid, target_cmid))

        # Update simulation to reflect the move
        simulated.remove(cmid)
        if target_cmid == 0:
            simulated.append(cmid)
        else:
            insert_pos = simulated.index(Cmid(target_cmid))
            simulated.insert(insert_pos, cmid)

    return moves


def diff(
    client: MoodleClientProtocol,
    course_id: CourseId,
    yaml_text: str,
    progress: ProgressCb | None = None,
) -> tuple[list[Change], list[str]]:
    """Compare yaml_text to live Moodle state.

    Returns (changes, warnings).
    changes  — ordered list of Change objects to apply
    warnings — list of human-readable warning strings

    Distinguishes four cases for every cmid:
      · Same section, same position  ->no change
      · Same section, different name/visible/position ->RENAME/HIDE/SHOW/MOVE_MODULE
      · Different section in YAML vs live ->MOVE_MODULE (cross-section)
      · In YAML but not in live      ->warning, cannot create
      · In live but absent from YAML ->warning, will NOT be deleted
    """
    parsed = yaml.safe_load(yaml_text)
    if not isinstance(parsed, dict):
        raise ValueError("Invalid YAML: expected a mapping at the top level")

    yaml_course_id = parsed.get("course_id")
    if yaml_course_id is not None and int(str(yaml_course_id)) != int(course_id):
        raise ValueError(
            f"YAML course_id={yaml_course_id} does not match --course {course_id}"
        )

    # Pre-count modules with settings for accurate progress reporting.
    _yaml_sections_preview = parsed.get("sections", [])
    _total_settings_mods = sum(
        1
        for sec in _yaml_sections_preview
        for mod in sec.get("modules", [])
        if isinstance(mod.get("settings"), dict) and mod["settings"]
    )
    _settings_idx = 0

    changes: list[Change] = []
    warnings: list[str] = []

    # ── Course-level settings diff ────────────────────────────────────────────
    yaml_course_settings = parsed.get("course")
    if isinstance(yaml_course_settings, dict) and yaml_course_settings:
        from moodlectl.features.courses import get_course_settings
        live_course_settings = get_course_settings(client, course_id)  # type: ignore[arg-type]
        changed_course = {
            k: v for k, v in yaml_course_settings.items()
            if str(v) != str(live_course_settings.get(k, ""))
        }
        if changed_course:
            keys_str = ", ".join(changed_course.keys())
            changes.append(Change(
                kind="UPDATE_COURSE",
                label=f"course {course_id}: update settings ({keys_str})",
                course_id=course_id,
                value=changed_course,
            ))

    live_sections = client.get_course_sections(course_id)
    live_by_section_id = {s["id"]: s for s in live_sections}

    # ── Global live maps ──────────────────────────────────────────────────────
    from moodlectl.types import CourseModule
    live_cmid_to_section: dict[Cmid, SectionId] = {}
    live_cmid_to_module: dict[Cmid, CourseModule] = {}
    for sec in live_sections:
        for mod in sec["modules"]:
            live_cmid_to_section[mod["cmid"]] = sec["id"]
            live_cmid_to_module[mod["cmid"]] = mod
    all_live_cmids: set[Cmid] = set(live_cmid_to_section)

    # ── Global YAML maps ──────────────────────────────────────────────────────
    yaml_sections_raw = parsed.get("sections", [])
    yaml_cmid_to_section: dict[Cmid, SectionId] = {}
    all_yaml_cmids: set[Cmid] = set()
    for yaml_sec in yaml_sections_raw:
        sec_id = SectionId(int(yaml_sec["id"]))
        for yaml_mod in yaml_sec.get("modules", []):
            raw_cmid = yaml_mod.get("cmid")
            if raw_cmid in (None, "", "new"):
                continue  # new module — no cmid yet
            cmid = Cmid(int(raw_cmid))
            all_yaml_cmids.add(cmid)
            yaml_cmid_to_section[cmid] = sec_id

    # ── Section ordering ──────────────────────────────────────────────────────
    yaml_section_order = [
        SectionId(int(s["id"])) for s in yaml_sections_raw
        if SectionId(int(s["id"])) in live_by_section_id
    ]
    live_section_order = [s["id"] for s in live_sections]
    live_sec_set = set(live_section_order)
    live_sec_filtered = [s for s in live_section_order if s in set(yaml_section_order)]
    yaml_sec_filtered = [s for s in yaml_section_order if s in live_sec_set]

    if yaml_sec_filtered != live_sec_filtered:
        for move_sec, before_sec in _compute_section_moves(yaml_sec_filtered, live_sec_filtered):
            changes.append(Change(
                kind="MOVE_SECTION",
                label=f"section {move_sec} ({live_by_section_id[move_sec]['name']!r}) -> before section {before_sec} ({live_by_section_id[before_sec]['name']!r})",
                section_id=move_sec,
                target_cmid=int(before_sec),
                course_id=course_id,
            ))

    # ── Global warnings ───────────────────────────────────────────────────────
    for cmid in sorted(all_yaml_cmids - all_live_cmids):
        warnings.append(f"cmid={cmid} not found in live course -- skipped (push cannot create modules)")

    for cmid in sorted(all_live_cmids - all_yaml_cmids):
        warnings.append(f"cmid={cmid} exists in live but is absent from YAML -- will NOT be deleted")

    # ── Per-section changes ───────────────────────────────────────────────────
    for yaml_sec in yaml_sections_raw:
        sec_id = SectionId(int(yaml_sec["id"]))
        live_sec = live_by_section_id.get(sec_id)
        if live_sec is None:
            warnings.append(f"Section id={sec_id} not found in live course -- skipped")
            continue

        # Section name
        yaml_name = str(yaml_sec.get("name", "")).strip()
        if yaml_name and yaml_name != live_sec["name"]:
            changes.append(Change(
                kind="RENAME_SECTION",
                label=f"section {sec_id}: {live_sec['name']!r} ->{yaml_name!r}",
                section_id=sec_id,
                value=yaml_name,
            ))

        # Section visibility
        yaml_sec_visible = bool(yaml_sec.get("visible", True))
        if yaml_sec_visible != live_sec["visible"]:
            kind = "SHOW_SECTION" if yaml_sec_visible else "HIDE_SECTION"
            changes.append(Change(
                kind=kind,
                label=f"section {sec_id}: {'show' if yaml_sec_visible else 'hide'} ({live_sec['name']!r})",
                section_id=sec_id,
            ))

        # Module name / visibility — runs for ALL yaml modules in this section that exist in live,
        # including those currently in a different section (cross-section move targets).
        for yaml_mod in yaml_sec.get("modules", []):
            raw_cmid = yaml_mod.get("cmid")
            if raw_cmid in (None, "", "new"):
                # New module — emit CREATE_MODULE.
                new_type = str(yaml_mod.get("type", "")).strip()
                new_name = str(yaml_mod.get("name", "")).strip()
                new_settings = yaml_mod.get("settings") or {}
                if not new_type:
                    warnings.append(f"section {sec_id}: skipping module with no 'type' field")
                    continue
                sec_num_for_create = live_sec["number"]
                changes.append(Change(
                    kind="CREATE_MODULE",
                    label=f"section {sec_id}: create {new_type} {new_name!r}",
                    course_id=course_id,
                    section_num=sec_num_for_create,
                    modname=new_type,
                    new_name=new_name,
                    new_settings=dict(new_settings) if isinstance(new_settings, dict) else {},
                ))
                continue
            cmid = Cmid(int(raw_cmid))
            if cmid not in all_live_cmids:
                continue  # already warned globally

            live_mod = live_cmid_to_module[cmid]

            yaml_mod_name = str(yaml_mod.get("name", "")).strip()
            if yaml_mod_name and yaml_mod_name != live_mod["name"]:
                changes.append(Change(
                    kind="RENAME_MODULE",
                    label=f"module cmid={cmid}: {live_mod['name']!r} ->{yaml_mod_name!r}",
                    cmid=cmid,
                    value=yaml_mod_name,
                ))

            yaml_mod_visible = bool(yaml_mod.get("visible", True))
            if yaml_mod_visible != live_mod["visible"]:
                kind = "SHOW_MODULE" if yaml_mod_visible else "HIDE_MODULE"
                changes.append(Change(
                    kind=kind,
                    label=f"module cmid={cmid}: {'show' if yaml_mod_visible else 'hide'} ({live_mod['name']!r})",
                    cmid=cmid,
                ))

            # Settings diff — compare each key in the YAML settings sub-dict.
            # We fetch the live form for this module so we can compare accurately.
            # skip entirely when the YAML settings block is absent or empty.
            yaml_settings = yaml_mod.get("settings")
            if isinstance(yaml_settings, dict) and yaml_settings:
                _settings_idx += 1
                if progress:
                    progress(_settings_idx, _total_settings_mods, live_mod["name"])
                try:
                    from moodlectl.client.api import _build_module_settings as _bms
                    live_form = client.get_module_form(cmid)  # type: ignore[attr-defined]
                    live_settings = _bms(live_form, live_mod["modname"])
                except Exception:
                    live_settings = {}
                changed_settings = {
                    k: v for k, v in yaml_settings.items()
                    if str(v) != str(live_settings.get(k, ""))
                }
                if changed_settings:
                    keys_str = ", ".join(changed_settings.keys())
                    changes.append(Change(
                        kind="UPDATE_MODULE",
                        label=f"module cmid={cmid}: update settings ({keys_str})",
                        cmid=cmid,
                        value=changed_settings,
                        modname=live_mod["modname"],
                    ))

        # ── Module ordering for this section ──────────────────────────────────
        # yaml_order: cmids listed in this YAML section that exist in live
        yaml_order = [
            Cmid(int(m["cmid"]))
            for m in yaml_sec.get("modules", [])
            if m.get("cmid") not in (None, "", "new")
            and Cmid(int(m["cmid"])) in all_live_cmids
        ]
        if not yaml_order:
            continue

        # Modules currently in this live section
        live_in_sec = [m["cmid"] for m in live_sec["modules"]]

        # Modules moving OUT (live has them here, but YAML puts them in another section)
        outgoing: set[Cmid] = {
            c for c in live_in_sec
            if c in yaml_cmid_to_section and yaml_cmid_to_section[c] != sec_id
        }

        # Modules moving IN (YAML puts them here, but live has them in another section)
        incoming: list[Cmid] = [
            c for c in yaml_order
            if live_cmid_to_section.get(c) != sec_id
        ]
        incoming_set = set(incoming)

        # Simulate post-cross-section-move state for this section:
        # Remove outgoing modules, append incoming at end (their arrival position before reorder)
        live_simulated = [c for c in live_in_sec if c not in outgoing] + incoming

        # Filter both sides to their mutual set (handles cmids absent from either side)
        sim_set = set(live_simulated)
        yaml_filtered = [c for c in yaml_order if c in sim_set]
        live_filtered = [c for c in live_simulated if c in set(yaml_filtered)]

        # Moves needed to go from live_filtered ->yaml_filtered
        moves = _compute_moves(yaml_filtered, live_filtered)
        moved_cmids = {m for m, _ in moves}

        for move_cmid, target in moves:
            if move_cmid in incoming_set:
                from_sec = live_cmid_to_section[move_cmid]
                label = (
                    f"module cmid={move_cmid}: move from section {from_sec} ->section {sec_id}"
                    + ("" if target == 0 else f" (before cmid={target})")
                )
            else:
                label = (
                    f"module cmid={move_cmid}: reorder within section {sec_id}"
                    + (" ->end" if target == 0 else f" ->before cmid={target}")
                )
            changes.append(Change(
                kind="MOVE_MODULE",
                label=label,
                cmid=move_cmid,
                section_id=sec_id,
                target_cmid=target,
                course_id=course_id,
            ))

        # Incoming modules not covered by _compute_moves (already at correct relative position
        # in the simulation — i.e., at end and YAML also wants them at end) still need a
        # cross-section MOVE_MODULE to physically move them here.
        for in_cmid in incoming:
            if in_cmid not in moved_cmids:
                from_sec = live_cmid_to_section[in_cmid]
                changes.append(Change(
                    kind="MOVE_MODULE",
                    label=f"module cmid={in_cmid}: move from section {from_sec} ->section {sec_id}",
                    cmid=in_cmid,
                    section_id=sec_id,
                    target_cmid=0,
                    course_id=course_id,
                ))

    return changes, warnings


def push(
    client: MoodleClientProtocol,
    changes: list[Change],
    progress: ProgressCb | None = None,
    continue_on_error: bool = False,
) -> list[tuple[Change, str]]:
    """Apply a list of Change objects to Moodle.

    Returns a list of (change, error_message) for changes that failed. An
    empty list means everything succeeded.

    continue_on_error=False (default): raises RuntimeError on the first failure
      with:
        · the 1-based index and total (e.g. "change 17/50")
        · the change kind and full human label from diff()
        · the attempted settings/value payload when applicable
        · the original exception's message (chained via __cause__)
    continue_on_error=True: collects failures, logs nothing itself, returns them
      so the caller can report the list.
    """
    total = len(changes)
    failures: list[tuple[Change, str]] = []
    for idx, change in enumerate(changes, 1):
        if progress:
            progress(idx, total, change.label)
        try:
            _apply_change(client, change)
        except Exception as exc:
            detail_lines = [
                f"change {idx}/{total} failed",
                f"  kind:   {change.kind}",
                f"  label:  {change.label}",
            ]
            if change.cmid is not None:
                detail_lines.append(f"  cmid:   {change.cmid}")
            if change.section_id is not None:
                detail_lines.append(f"  section_id: {change.section_id}")
            if change.modname:
                detail_lines.append(f"  modname: {change.modname}")
            if isinstance(change.value, dict):
                keys = ", ".join(sorted(change.value.keys()))
                detail_lines.append(f"  fields: {keys}")
            elif change.value is not None:
                detail_lines.append(f"  value:  {change.value!r}")
            detail_lines.append(f"  error:  {exc}")
            msg = "\n".join(detail_lines)
            if continue_on_error:
                failures.append((change, msg))
                continue
            raise RuntimeError(msg) from exc
    return failures


def _apply_change(client: MoodleClientProtocol, change: Change) -> None:
    """Dispatch a single change to the appropriate client method."""
    if change.kind == "RENAME_MODULE" and change.cmid is not None:
        client.rename_module(change.cmid, str(change.value))
    elif change.kind == "RENAME_SECTION" and change.section_id is not None:
        client.rename_section(change.section_id, str(change.value))
    elif change.kind == "HIDE_MODULE" and change.cmid is not None:
        client.set_module_visible(change.cmid, False)
    elif change.kind == "SHOW_MODULE" and change.cmid is not None:
        client.set_module_visible(change.cmid, True)
    elif change.kind == "HIDE_SECTION" and change.section_id is not None:
        client.set_section_visible(change.section_id, False)
    elif change.kind == "SHOW_SECTION" and change.section_id is not None:
        client.set_section_visible(change.section_id, True)
    elif change.kind == "UPDATE_MODULE" and change.cmid is not None and isinstance(change.value, dict):
        from moodlectl.client.api import _settings_to_form
        form_changes = _settings_to_form(change.modname, change.value)
        client.update_module(change.cmid, form_changes)
    elif change.kind == "UPDATE_COURSE" and change.course_id is not None and isinstance(change.value, dict):
        from moodlectl.client.api import _course_settings_to_form
        form_changes = _course_settings_to_form(change.value)
        client.update_course(change.course_id, form_changes)
    elif (
        change.kind == "MOVE_SECTION"
        and change.section_id is not None
        and change.course_id is not None
    ):
        client.move_section(change.course_id, change.section_id, SectionId(change.target_cmid))
    elif (
        change.kind == "CREATE_MODULE"
        and change.course_id is not None
        and change.section_num is not None
        and change.modname
    ):
        client.create_module(
            change.course_id, change.section_num, change.modname,
            change.new_name, change.new_settings or {},
        )
    elif (
        change.kind == "MOVE_MODULE"
        and change.cmid is not None
        and change.section_id is not None
        and change.course_id is not None
    ):
        client.move_module(change.course_id, change.cmid, change.target_cmid, change.section_id)
    else:
        raise RuntimeError(
            f"unknown or incomplete change: kind={change.kind} "
            f"cmid={change.cmid} section_id={change.section_id}"
        )
