"""YAML pull/diff/push for the Moodle gradebook setup.

Phase 1 (read-only): `pull()` only — serialise a course's full gradebook
(categories + grade items + calculations) to a YAML string suitable for
inspection or later round-trip via Phase 2/3 `diff()` / `push()`.

The serialised shape mirrors the live tree exactly: categories nest their
subcategories and items in the same order Moodle renders them. Identity is
carried by `eid` (e.g. `cg1524`, `ig7166`); pure-string keys allow YAML
editors to safely round-trip the file without quoting concerns.

`features/content_yaml.py` is the sibling pattern this module imitates.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable

import yaml

from moodlectl.types import (
    AGGREGATION_BY_NAME,
    CourseId,
    GradeCategory,
    GradeCategoryId,
    GradeItem,
    GradeItemId,
    GradeTree,
    MoodleClientProtocol,
)

# Progress callback: (current, total, description) -> None
ProgressCb = Callable[[int, int, str], None]


_HEADER = """\
# Generated by moodlectl gradebook pull.
#
# Editable on a future `gradebook push`:
#   - category: name, aggregation, droplow, keephigh, grademax, weight,
#     weight_override, hidden, idnumber, aggregateonlygraded
#   - item:     name (manual only), grademax (manual only), weight,
#     weight_override, hidden, idnumber, calculation (any item)
#   - structure: nest order; manual items may be added/removed
#
# Read-only (round-tripped verbatim):
#   - course_id, eid (cgN / igN), item_id, cmid, kind ("quiz" / "assign" /
#     "manual" / "calculated" / "mod")
#
# Aggregation names: sum, mean, mean_of_grades, median, min, max, mode,
#   weighted_mean, simple_weighted_mean
#
# Tip: commit this file to git before any future push — that is your undo.
"""


# ---------------------------------------------------------------------------
# Serialisation helpers
# ---------------------------------------------------------------------------

def _round(x: float | None) -> float | None:
    if x is None:
        return None
    # Strip Moodle's trailing zeros (20.00000) without losing precision.
    return round(float(x), 5)


def _enrich_category(
        client: MoodleClientProtocol,
        course_id: CourseId,
        cat: GradeCategory,
        progress: ProgressCb | None,
        counter: list[int],
        total: int,
) -> None:
    """Fetch per-category settings (droplow, idnumber, …) from category.php."""
    counter[0] += 1
    if progress:
        progress(counter[0], total, f"category: {cat['name']}")
    form = client.get_grade_category_form(course_id, cat["cat_id"])  # type: ignore[arg-type]
    cat["droplow"] = int(form.get("droplow") or 0)
    cat["keephigh"] = int(form.get("keephigh") or 0)
    cat["aggregateonlygraded"] = bool(int(form.get("aggregateonlygraded") or 0))
    cat["aggregateoutcomes"] = bool(int(form.get("aggregateoutcomes") or 0))
    cat["idnumber"] = form.get("grade_item_idnumber") or ""
    coef2 = form.get("grade_item_aggregationcoef2") or ""
    cat["aggregationcoef2"] = float(coef2) if coef2 else None
    coef = form.get("grade_item_aggregationcoef") or ""
    cat["weight"] = float(coef) if coef and coef != "0" else None
    cat["weight_override"] = bool(int(form.get("grade_item_weightoverride") or 0))
    # A category's grade_item may carry a calculation override; capture it.
    try:
        formula, _ = client.get_grade_calculation(course_id, cat["item_id"])  # type: ignore[arg-type]
    except Exception:
        formula = ""
    if formula:
        cat["calculation"] = formula


def _enrich_item(
        client: MoodleClientProtocol,
        course_id: CourseId,
        item: GradeItem,
        progress: ProgressCb | None,
        counter: list[int],
        total: int,
) -> None:
    """Fetch per-item settings (idnumber, calculation, …) from item.php + calculation.php."""
    counter[0] += 1
    if progress:
        progress(counter[0], total, f"item: {item['name']}")
    form = client.get_grade_item_form(course_id, item["item_id"])  # type: ignore[arg-type]
    item["idnumber"] = form.get("idnumber") or ""
    coef2 = form.get("aggregationcoef2") or ""
    item["aggregationcoef2"] = float(coef2) if coef2 else None
    coef = form.get("aggregationcoef") or ""
    item["weight"] = float(coef) if coef and coef != "0" else None
    item["weight_override"] = bool(int(form.get("weightoverride") or 0))
    item["locked"] = bool(int(form.get("locked") or 0))

    # Only manual items can hold a calculation. Activity-backed items can too,
    # but it's rare; fetch defensively. Skip categoryitem/courseitem (handled
    # at category level).
    try:
        formula, _ref_idmap = client.get_grade_calculation(course_id, item["item_id"])  # type: ignore[arg-type]
    except Exception:
        formula = ""
    item["calculation"] = formula or ""
    if formula:
        # Reclassify manual items that actually carry a formula.
        if item["kind"] == "manual":
            item["kind"] = "calculated"


def _walk_count(cat: GradeCategory) -> int:
    """Return the total number of form fetches required to enrich this tree."""
    n = 1  # the category itself
    for sub in cat["subcategories"]:
        n += _walk_count(sub)
    n += len(cat["items"])
    return n


def _enrich_tree(
        client: MoodleClientProtocol,
        course_id: CourseId,
        cat: GradeCategory,
        progress: ProgressCb | None,
        counter: list[int],
        total: int,
) -> None:
    _enrich_category(client, course_id, cat, progress, counter, total)
    for sub in cat["subcategories"]:
        _enrich_tree(client, course_id, sub, progress, counter, total)
    for item in cat["items"]:
        _enrich_item(client, course_id, item, progress, counter, total)


def _item_to_yaml(item: GradeItem) -> dict[str, Any]:
    out: dict[str, Any] = {
        "eid": item["eid"],
        "item_id": int(item["item_id"]),
        "name": item["name"],
        "kind": item["kind"],
        "grademax": _round(item.get("grademax")),
    }
    cmid = item.get("cmid")
    if cmid:
        out["cmid"] = int(cmid)
    idn = item.get("idnumber") or ""
    if idn:
        out["idnumber"] = idn
    if item.get("weight_override"):
        out["weight_override"] = True
        if item.get("weight") is not None:
            out["weight"] = _round(item["weight"])
    coef2 = item.get("aggregationcoef2")
    if coef2 is not None:
        out["aggregationcoef2"] = _round(coef2)
    if item.get("hidden"):
        out["hidden"] = True
    if item.get("locked"):
        out["locked"] = True
    # module_visible only meaningful for activity-backed items; default True so
    # the YAML stays tidy and round-trips for items we couldn't probe.
    if cmid and item.get("module_visible") is False:
        out["module_visible"] = False
    calc = item.get("calculation") or ""
    if calc:
        out["calculation"] = calc
    return out


def _category_to_yaml(cat: GradeCategory) -> dict[str, Any]:
    out: dict[str, Any] = {
        "eid": cat["eid"],
        "cat_id": int(cat["cat_id"]),
        "item_id": int(cat["item_id"]),
        "name": cat["name"],
        "aggregation": cat["aggregation"],
        "grademax": _round(cat.get("grademax")),
    }
    idn = cat.get("idnumber") or ""
    if idn:
        out["idnumber"] = idn
    if cat.get("droplow"):
        out["droplow"] = int(cat["droplow"])
    if cat.get("keephigh"):
        out["keephigh"] = int(cat["keephigh"])
    if not cat.get("aggregateonlygraded", True):
        out["aggregateonlygraded"] = False
    if cat.get("aggregateoutcomes"):
        out["aggregateoutcomes"] = True
    if cat.get("weight_override"):
        out["weight_override"] = True
        if cat.get("weight") is not None:
            out["weight"] = _round(cat["weight"])
    coef2 = cat.get("aggregationcoef2")
    if coef2 is not None:
        out["aggregationcoef2"] = _round(coef2)
    if cat.get("hidden"):
        out["hidden"] = True
    calc = cat.get("calculation") or ""
    if calc:
        out["calculation"] = calc

    children: list[dict[str, Any]] = []
    for sub in cat["subcategories"]:
        children.append({"category": _category_to_yaml(sub)})
    for item in cat["items"]:
        children.append({"item": _item_to_yaml(item)})
    if children:
        out["children"] = children
    return out


def pull(
        client: MoodleClientProtocol,
        course_id: CourseId,
        progress: ProgressCb | None = None,
) -> str:
    """Return a YAML string representing the current gradebook state."""
    tree: GradeTree = client.get_gradebook_tree(course_id)  # type: ignore[call-arg]
    total = _walk_count(tree["root"])
    counter = [0]
    _enrich_tree(client, course_id, tree["root"], progress, counter, total)
    _enrich_module_visibility(client, course_id, tree["root"])

    data: dict[str, Any] = {
        "course_id": int(course_id),
        "root": _category_to_yaml(tree["root"]),
    }
    yaml_text = yaml.safe_dump(
        data, sort_keys=False, allow_unicode=True, default_flow_style=False, width=120,
    )
    return _HEADER + yaml_text


def _enrich_module_visibility(
        client: MoodleClientProtocol,
        course_id: CourseId,
        root: GradeCategory,
) -> None:
    """Fill `module_visible` on activity-backed items using the course sections.

    One HTTP request fetches every section + module status, so this is cheap
    even on big courses — we don't add a request per item.
    """
    try:
        sections = client.get_course_sections(course_id)  # type: ignore[call-arg]
    except Exception:
        return
    visible_by_cmid: dict[int, bool] = {}
    for sec in sections:
        for m in sec.get("modules", []) or []:
            visible_by_cmid[int(m["cmid"])] = bool(m.get("visible", True))

    def _walk(cat: GradeCategory) -> None:
        for it in cat["items"]:
            cmid = it.get("cmid")
            if cmid and int(cmid) in visible_by_cmid:
                it["module_visible"] = visible_by_cmid[int(cmid)]
        for sub in cat["subcategories"]:
            _walk(sub)

    _walk(root)


# ---------------------------------------------------------------------------
# Pretty-printer for `gradebook show` — operates on the same enriched tree.
# ---------------------------------------------------------------------------

def render_tree(tree: GradeTree) -> str:
    """Return a human-readable indented summary of the gradebook tree.

    Used by `moodlectl gradebook show`. Does NOT fetch per-node forms — only
    information present on the live tree page is shown (no droplow/idnumber).
    """
    lines: list[str] = []

    def fmt_cat(cat: GradeCategory, depth: int) -> None:
        pad = "  " * depth
        weight = f" w={cat['weight']:g}" if cat.get("weight") else ""
        hidden = "  [hidden]" if cat.get("hidden") else ""
        lines.append(
            f"{pad}[{cat['eid']}] {cat['name']}  "
            f"(agg={cat['aggregation']}, max={cat.get('grademax', 0):g}{weight}){hidden}"
        )
        for sub in cat["subcategories"]:
            fmt_cat(sub, depth + 1)
        for it in cat["items"]:
            ipad = "  " * (depth + 1)
            kind = it.get("kind", "?")
            weight = f" w={it['weight']:g}" if it.get("weight") else ""
            cmid = f" cmid={it['cmid']}" if it.get("cmid") else ""
            hidden = "  [hidden]" if it.get("hidden") else ""
            lines.append(
                f"{ipad}- [{it['eid']}] {it['name']}  "
                f"({kind}, max={it.get('grademax', 0):g}{weight}{cmid}){hidden}"
            )

    fmt_cat(tree["root"], 0)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Phase 2 — diff: parsed YAML  →  list[Change]
# ---------------------------------------------------------------------------

# Change kinds
CREATE_CATEGORY = "CREATE_CATEGORY"
UPDATE_CATEGORY = "UPDATE_CATEGORY"
CREATE_ITEM = "CREATE_ITEM"
UPDATE_ITEM = "UPDATE_ITEM"
MOVE_ITEM = "MOVE_ITEM"
SET_CALCULATION = "SET_CALCULATION"
DELETE_ITEM = "DELETE_ITEM"
SET_MODULE_VISIBLE = "SET_MODULE_VISIBLE"


@dataclass
class Change:
    """A single declarative operation to apply against the gradebook.

    `target_eid` identifies the live node when known (eid like "cg12" or
    "ig345"). For CREATE_*, target_eid is "" and `parent_cat_id` carries the
    intended parent. `payload` holds the Moodle form-field changes verbatim
    (already translated from friendly YAML names to Moodle's form keys).
    """
    kind: str
    label: str  # human-readable, shown in the diff summary
    payload: dict[str, str] = field(default_factory=dict)
    target_eid: str = ""
    target_item_id: int = 0      # for SET_CALCULATION + UPDATE_ITEM
    target_cat_id: int = 0       # for UPDATE_CATEGORY
    parent_cat_id: int = 0       # for CREATE_*
    # SET_CALCULATION extras
    formula: str = ""
    idnumber_overrides: dict[int, str] = field(default_factory=dict)
    # CREATE_ITEM extras — the YAML node so push() can wire up calculation/idnumber afterwards
    yaml_node: dict[str, Any] = field(default_factory=dict)
    # MOVE_ITEM extras
    target_parent_cat_id: int = 0   # destination category
    # Two-pass push support: when the parent category was CREATED in the same
    # push, target_parent_cat_id starts at 0 and `pending_parent_tag` carries
    # a stable label that resolves to the real cat_id at apply time.
    pending_parent_tag: str = ""
    # CREATE_CATEGORY emits its own tag so dependent operations can resolve it.
    own_tag: str = ""
    # When set, push routes the idnumber update through the calc-form trick
    # (item.php silently ignores idnumber on activity-backed grade items).
    via_calc_form: bool = False
    course_total_item_id: int = 0   # filled at push time


# ── Helpers ───────────────────────────────────────────────────────────────

def _flatten_live(cat: GradeCategory) -> tuple[dict[str, GradeCategory], dict[str, GradeItem]]:
    """Return ({eid: category}, {eid: item}) for every node under cat (inclusive)."""
    cats: dict[str, GradeCategory] = {cat["eid"]: cat}
    items: dict[str, GradeItem] = {}
    for sub in cat["subcategories"]:
        sub_cats, sub_items = _flatten_live(sub)
        cats.update(sub_cats)
        items.update(sub_items)
    for it in cat["items"]:
        items[it["eid"]] = it
    return cats, items


def _live_item_by_cmid(items: dict[str, GradeItem]) -> dict[int, GradeItem]:
    return {int(it["cmid"]): it for it in items.values() if it.get("cmid")}


def _live_item_by_idnumber(items: dict[str, GradeItem]) -> dict[str, GradeItem]:
    return {it["idnumber"]: it for it in items.values() if it.get("idnumber")}


def _match_item(node: dict[str, Any], live_items: dict[str, GradeItem]) -> GradeItem | None:
    """Find a live item matching the YAML node by (in priority order) eid, cmid, idnumber."""
    eid = node.get("eid")
    if eid and eid in live_items:
        return live_items[eid]
    cmid = node.get("cmid")
    if cmid:
        by_cmid = _live_item_by_cmid(live_items)
        if int(cmid) in by_cmid:
            return by_cmid[int(cmid)]
    idnum = node.get("idnumber")
    if idnum:
        by_idn = _live_item_by_idnumber(live_items)
        if idnum in by_idn:
            return by_idn[idnum]
    return None


def _walk_yaml(
        node: dict[str, Any],
        parent_cat_id: int,
        live_cats: dict[str, GradeCategory],
        live_items: dict[str, GradeItem],
        changes: list[Change],
        parent_tag: str = "",
) -> None:
    """Recursively diff a YAML category node into Change objects.

    `parent_tag` is non-empty when the parent category is being CREATED in
    this same push (not yet in the live tree). Children inherit the tag so
    push() can resolve their real parent cat_id after the CREATE succeeds.
    """
    eid = node.get("eid", "")
    yaml_name = node.get("name", "")

    live: GradeCategory | None = live_cats.get(eid) if eid else None

    if live is None:
        # CREATE_CATEGORY — emit a stable tag children can refer back to.
        own_tag = f"__pending_cat_{id(node):x}__"
        payload = _category_yaml_to_form_changes(node, include_required=True)
        changes.append(Change(
            kind=CREATE_CATEGORY,
            label=f"create category {yaml_name!r} under cat#{parent_cat_id}",
            payload=payload,
            parent_cat_id=parent_cat_id,
            pending_parent_tag=parent_tag,  # parent might also be brand-new
            own_tag=own_tag,
            yaml_node=node,
        ))
        new_parent = 0
        new_parent_tag = own_tag
    else:
        # UPDATE_CATEGORY if attributes differ
        payload = _category_diff_payload(node, live)
        if payload:
            changes.append(Change(
                kind=UPDATE_CATEGORY,
                label=f"update category {live['name']!r} ({eid}): {sorted(payload)}",
                payload=payload,
                target_eid=eid,
                target_cat_id=int(live["cat_id"]),
            ))
        # Calculation override on the category's grade_item
        yaml_calc = (node.get("calculation") or "").strip()
        live_calc = (live.get("calculation") or "").strip()
        if yaml_calc != live_calc:
            changes.append(Change(
                kind=SET_CALCULATION,
                label=f"set calculation on category {live['name']!r} ({eid})",
                target_eid=eid,
                target_item_id=int(live["item_id"]),
                formula=yaml_calc,
            ))
        new_parent = int(live["cat_id"])
        new_parent_tag = ""

    # Recurse children
    for child_wrapper in node.get("children", []) or []:
        if "category" in child_wrapper:
            _walk_yaml(child_wrapper["category"], new_parent, live_cats, live_items, changes, parent_tag=new_parent_tag)
        elif "item" in child_wrapper:
            _diff_item(child_wrapper["item"], new_parent, live_items, changes, parent_tag=new_parent_tag)


def _diff_item(
        node: dict[str, Any],
        parent_cat_id: int,
        live_items: dict[str, GradeItem],
        changes: list[Change],
        parent_tag: str = "",
) -> None:
    live = _match_item(node, live_items)
    if live is None:
        kind = node.get("kind", "manual")
        if kind not in ("manual", "calculated"):
            # We can't create activity-backed items via the gradebook UI — they
            # come from creating the underlying module (assign/quiz). Skip with
            # a warning embedded in label so the user notices in the diff.
            changes.append(Change(
                kind=CREATE_ITEM,
                label=f"SKIP create {kind!r} item {node.get('name')!r} (must be created via the module)",
                payload={},
                parent_cat_id=parent_cat_id,
                pending_parent_tag=parent_tag,
                yaml_node=node,
            ))
            return
        payload = _item_yaml_to_form_changes(node, include_required=True)
        changes.append(Change(
            kind=CREATE_ITEM,
            label=f"create {kind} item {node.get('name')!r} under cat#{parent_cat_id} (max={node.get('grademax')})",
            payload=payload,
            parent_cat_id=parent_cat_id,
            pending_parent_tag=parent_tag,
            yaml_node=node,
        ))
        return

    # Detect MOVE: the YAML wraps this item under a parent category whose
    # cat_id differs from the live parent. parent_cat_id is the cat_id of
    # the enclosing YAML category node.
    live_parent = int(live.get("parent_cat_id") or 0)
    # A move is needed when either:
    #  - parent_cat_id is concrete and differs from live, OR
    #  - parent_cat_id == 0 (sentinel) but we have a pending_parent_tag —
    #    meaning the parent is being created in this same push.
    needs_move = (parent_cat_id and parent_cat_id != live_parent) or (
            not parent_cat_id and parent_tag and live_parent
    )
    if needs_move:
        changes.append(Change(
            kind=MOVE_ITEM,
            label=(f"move item {live['name']!r} ({live['eid']}) "
                   f"→ {'new cat (' + parent_tag + ')' if parent_tag else f'cat#{parent_cat_id}'}"),
            target_eid=live["eid"],
            target_item_id=int(live["item_id"]),
            target_parent_cat_id=parent_cat_id,
            pending_parent_tag=parent_tag,
        ))

    # SET_MODULE_VISIBLE: activity items can change `module_visible` (default True).
    if live.get("cmid"):
        yaml_vis = node.get("module_visible")
        live_vis = live.get("module_visible", True)
        if yaml_vis is not None and bool(yaml_vis) != bool(live_vis):
            changes.append(Change(
                kind=SET_MODULE_VISIBLE,
                label=(f"set module {'visible' if yaml_vis else 'hidden'} on "
                       f"{live['name']!r} (cmid={live['cmid']})"),
                target_eid=live["eid"],
                target_item_id=int(live["item_id"]),
                payload={"cmid": str(int(live["cmid"])), "visible": "1" if yaml_vis else "0"},
            ))

    payload = _item_diff_payload(node, live)
    # For activity-backed items, idnumber changes must be routed through the
    # calc-form override mechanism (item.php silently ignores them). Split
    # off idnumber into a separate Change so push handles it correctly.
    is_activity_backed = bool(live.get("cmid"))
    if payload and "idnumber" in payload and is_activity_backed:
        new_idnumber = payload.pop("idnumber")
        changes.append(Change(
            kind=UPDATE_ITEM,
            label=f"set idnumber on activity item {live['name']!r} ({live['eid']}) → {new_idnumber!r}",
            payload={"idnumber": new_idnumber},
            target_eid=live["eid"],
            target_item_id=int(live["item_id"]),
            via_calc_form=True,
        ))

    if payload:
        changes.append(Change(
            kind=UPDATE_ITEM,
            label=f"update item {live['name']!r} ({live['eid']}): {sorted(payload)}",
            payload=payload,
            target_eid=live["eid"],
            target_item_id=int(live["item_id"]),
        ))
    yaml_calc = (node.get("calculation") or "").strip()
    live_calc = (live.get("calculation") or "").strip()
    if yaml_calc != live_calc:
        changes.append(Change(
            kind=SET_CALCULATION,
            label=f"set calculation on item {live['name']!r} ({live['eid']})",
            target_eid=live["eid"],
            target_item_id=int(live["item_id"]),
            formula=yaml_calc,
        ))


# ── YAML-friendly  ↔  Moodle form key translation ────────────────────────

def _category_yaml_to_form_changes(node: dict[str, Any], *, include_required: bool) -> dict[str, str]:
    """Translate a YAML category dict to Moodle category.php form-field changes.

    `include_required=True` is used for CREATE (must include `fullname` and
    `aggregation`); UPDATE callers omit fields they don't want to change.
    """
    out: dict[str, str] = {}
    if "name" in node or include_required:
        out["fullname"] = str(node.get("name", ""))
    if "aggregation" in node or include_required:
        agg_name = node.get("aggregation", "sum")
        out["aggregation"] = str(AGGREGATION_BY_NAME[agg_name])
    if "droplow" in node:
        out["droplow"] = str(int(node["droplow"]))
    if "keephigh" in node:
        out["keephigh"] = str(int(node["keephigh"]))
    if "aggregateonlygraded" in node:
        out["aggregateonlygraded"] = "1" if node["aggregateonlygraded"] else "0"
    if "aggregateoutcomes" in node:
        out["aggregateoutcomes"] = "1" if node["aggregateoutcomes"] else "0"
    if "grademax" in node:
        out["grade_item_grademax"] = f"{float(node['grademax']):.2f}"
    if "idnumber" in node:
        out["grade_item_idnumber"] = str(node["idnumber"])
    if "hidden" in node:
        out["grade_item_hidden"] = "1" if node["hidden"] else "0"
    if "weight_override" in node:
        out["grade_item_weightoverride"] = "1" if node["weight_override"] else "0"
    if "weight" in node and node["weight"] is not None:
        out["grade_item_aggregationcoef"] = f"{float(node['weight']):.4f}"
    if "aggregationcoef2" in node and node["aggregationcoef2"] is not None:
        out["grade_item_aggregationcoef2"] = f"{float(node['aggregationcoef2']):.4f}"
    return out


def _category_diff_payload(node: dict[str, Any], live: GradeCategory) -> dict[str, str]:
    """Return only the form-field changes for an UPDATE (differs from live)."""
    out: dict[str, str] = {}
    if "name" in node and node["name"] != live["name"]:
        out["fullname"] = str(node["name"])
    if "aggregation" in node and node["aggregation"] != live["aggregation"]:
        out["aggregation"] = str(AGGREGATION_BY_NAME[node["aggregation"]])
    if "droplow" in node and int(node["droplow"]) != int(live.get("droplow") or 0):
        out["droplow"] = str(int(node["droplow"]))
    if "keephigh" in node and int(node["keephigh"]) != int(live.get("keephigh") or 0):
        out["keephigh"] = str(int(node["keephigh"]))
    if "grademax" in node and abs(float(node["grademax"]) - float(live.get("grademax", 0.0))) > 1e-6:
        out["grade_item_grademax"] = f"{float(node['grademax']):.2f}"
    if "idnumber" in node and str(node["idnumber"]) != str(live.get("idnumber") or ""):
        out["grade_item_idnumber"] = str(node["idnumber"])
    if "hidden" in node and bool(node["hidden"]) != bool(live.get("hidden")):
        out["grade_item_hidden"] = "1" if node["hidden"] else "0"
    if "weight_override" in node and bool(node["weight_override"]) != bool(live.get("weight_override")):
        out["grade_item_weightoverride"] = "1" if node["weight_override"] else "0"
    if "weight" in node and node["weight"] is not None:
        live_w = live.get("weight")
        if live_w is None or abs(float(node["weight"]) - float(live_w)) > 1e-6:
            out["grade_item_aggregationcoef"] = f"{float(node['weight']):.4f}"
    if "aggregationcoef2" in node and node["aggregationcoef2"] is not None:
        live_c = live.get("aggregationcoef2")
        if live_c is None or abs(float(node["aggregationcoef2"]) - float(live_c)) > 1e-6:
            out["grade_item_aggregationcoef2"] = f"{float(node['aggregationcoef2']):.4f}"
    return out


def _item_yaml_to_form_changes(node: dict[str, Any], *, include_required: bool) -> dict[str, str]:
    """Translate a YAML item dict to Moodle item.php form-field changes.

    Note: item.php uses bare keys (`itemname`, `idnumber`, `grademax`), not
    `grade_item_*` prefixed (those are category.php-only).
    """
    out: dict[str, str] = {}
    if "name" in node or include_required:
        out["itemname"] = str(node.get("name", ""))
    if "grademax" in node or include_required:
        out["grademax"] = f"{float(node.get('grademax', 0.0)):.2f}"
    if "idnumber" in node:
        out["idnumber"] = str(node["idnumber"])
    if "hidden" in node:
        out["hidden"] = "1" if node["hidden"] else "0"
    if "locked" in node:
        out["locked"] = "1" if node["locked"] else "0"
    if "weight_override" in node:
        out["weightoverride"] = "1" if node["weight_override"] else "0"
    if "weight" in node and node["weight"] is not None:
        out["aggregationcoef"] = f"{float(node['weight']):.4f}"
    if "aggregationcoef2" in node and node["aggregationcoef2"] is not None:
        out["aggregationcoef2"] = f"{float(node['aggregationcoef2']):.4f}"
    # `itemtype` is required for create; manual is the only user-creatable kind.
    if include_required:
        out["itemtype"] = "manual"
    return out


def _item_diff_payload(node: dict[str, Any], live: GradeItem) -> dict[str, str]:
    out: dict[str, str] = {}
    # Name is editable only on manual/calculated items — Moodle silently
    # ignores name changes on activity-backed items. Emit anyway and let the
    # form swallow it.
    if "name" in node and node["name"] != live["name"]:
        out["itemname"] = str(node["name"])
    if "grademax" in node and abs(float(node["grademax"]) - float(live.get("grademax", 0.0))) > 1e-6:
        out["grademax"] = f"{float(node['grademax']):.2f}"
    if "idnumber" in node and str(node["idnumber"]) != str(live.get("idnumber") or ""):
        out["idnumber"] = str(node["idnumber"])
    if "hidden" in node and bool(node["hidden"]) != bool(live.get("hidden")):
        out["hidden"] = "1" if node["hidden"] else "0"
    if "locked" in node and bool(node["locked"]) != bool(live.get("locked")):
        out["locked"] = "1" if node["locked"] else "0"
    if "weight_override" in node and bool(node["weight_override"]) != bool(live.get("weight_override")):
        out["weightoverride"] = "1" if node["weight_override"] else "0"
    if "weight" in node and node["weight"] is not None:
        live_w = live.get("weight")
        if live_w is None or abs(float(node["weight"]) - float(live_w)) > 1e-6:
            out["aggregationcoef"] = f"{float(node['weight']):.4f}"
    if "aggregationcoef2" in node and node["aggregationcoef2"] is not None:
        live_c = live.get("aggregationcoef2")
        if live_c is None or abs(float(node["aggregationcoef2"]) - float(live_c)) > 1e-6:
            out["aggregationcoef2"] = f"{float(node['aggregationcoef2']):.4f}"
    return out


def _collect_yaml_item_ids(node: dict[str, Any]) -> set[int]:
    """Walk a YAML root and return every referenced item_id (eid or item_id field)."""
    ids: set[int] = set()
    for child in node.get("children", []) or []:
        if "category" in child:
            ids |= _collect_yaml_item_ids(child["category"])
        elif "item" in child:
            it = child["item"]
            iid = it.get("item_id") or (int(it["eid"][2:]) if it.get("eid", "").startswith("ig") else None)
            if iid:
                ids.add(int(iid))
    return ids


def diff(
        client: MoodleClientProtocol,
        course_id: CourseId,
        yaml_text: str,
        *,
        live_tree: GradeTree | None = None,
) -> list[Change]:
    """Compare parsed YAML against the live gradebook; return ordered Change list.

    `live_tree` is accepted for tests / reuse; if omitted, pulled via the
    client (no per-form enrichment — only structural diffing of attributes
    available on the tree page plus calculations on category nodes).
    """
    parsed = yaml.safe_load(yaml_text)
    if not isinstance(parsed, dict) or "root" not in parsed:
        raise ValueError("YAML must have a top-level `root:` category node.")

    if live_tree is None:
        live_tree = client.get_gradebook_tree(course_id)  # type: ignore[call-arg]
        # Enrich with droplow/idnumber/calculation so the diff catches them
        total = _walk_count(live_tree["root"])
        counter = [0]
        _enrich_tree(client, course_id, live_tree["root"], None, counter, total)

    live_cats, live_items = _flatten_live(live_tree["root"])
    changes: list[Change] = []
    _walk_yaml(parsed["root"], int(live_tree["root"]["cat_id"]), live_cats, live_items, changes)

    # DELETE_ITEM: any live item not referenced in YAML AND with a cmid
    # (activity-backed → can be deleted via delete_module). Manual items
    # without a YAML match are skipped — Moodle doesn't expose web delete
    # for them and we'd just produce a useless Change.
    yaml_item_ids = _collect_yaml_item_ids(parsed["root"])
    for live_item in live_items.values():
        if int(live_item["item_id"]) in yaml_item_ids:
            continue
        cmid = live_item.get("cmid")
        if not cmid:
            # Manual item missing from YAML — refuse to emit a Change (would fail).
            continue
        changes.append(Change(
            kind=DELETE_ITEM,
            label=f"DELETE activity item {live_item['name']!r} ({live_item['eid']}, cmid={cmid})",
            target_eid=live_item["eid"],
            target_item_id=int(live_item["item_id"]),
            payload={"cmid": str(int(cmid))},
        ))

    return _order_changes(changes)


def _order_changes(changes: list[Change]) -> list[Change]:
    """Order changes so dependencies are satisfied at apply time.

    1. CREATE_CATEGORY (parent-before-child preserved by YAML walk order)
    2. CREATE_ITEM (manual items must exist before calculations reference them)
    3. UPDATE_CATEGORY
    4. UPDATE_ITEM
    5. SET_CALCULATION (last; idnumbers may have been just-set by UPDATE_ITEM)
    """
    order = {
        CREATE_CATEGORY: 0,
        CREATE_ITEM: 1,
        MOVE_ITEM: 2,            # before UPDATE/CALC so the item lives in its target category first
        UPDATE_CATEGORY: 3,
        UPDATE_ITEM: 4,
        SET_MODULE_VISIBLE: 5,   # after item updates (visibility lives on the module, not gradebook)
        SET_CALCULATION: 6,
        DELETE_ITEM: 7,          # last — removing items can break references; do after everything else
    }
    return sorted(changes, key=lambda c: order.get(c.kind, 99))


def push(
        client: MoodleClientProtocol,
        course_id: CourseId,
        changes: list[Change],
        *,
        progress: ProgressCb | None = None,
        continue_on_error: bool = False,
) -> list[tuple[Change, str]]:
    """Apply a list of Changes against Moodle. Returns [(change, error_msg), ...] for failures.

    Empty return list = all succeeded. With `continue_on_error=True`, push
    keeps going after a failure and reports everything at the end; otherwise
    the first failure raises.
    """
    failures: list[tuple[Change, str]] = []
    total = len(changes)
    # Maps used to resolve newly-created node ids inside this push session.
    created_cats_by_tag: dict[str, int] = {}    # own_tag → resolved cat_id
    created_cats: dict[str, int] = {}           # name → cat_id (legacy lookup)
    created_items: dict[str, int] = {}          # name → item_id

    # Find the course-total grade_item_id once — needed for the calc-form
    # idnumber trick on activity-backed items.
    course_total_item_id = _find_course_total_item_id(client, course_id)

    for i, ch in enumerate(changes, 1):
        if progress:
            progress(i, total, ch.label[:60])
        ch.course_total_item_id = course_total_item_id
        try:
            _apply_one(client, course_id, ch, created_cats, created_cats_by_tag, created_items)
        except Exception as exc:  # noqa: BLE001
            if continue_on_error:
                failures.append((ch, str(exc)))
                continue
            raise
    return failures


def _find_course_total_item_id(
        client: MoodleClientProtocol, course_id: CourseId,
) -> int:
    """Resolve the course-total grade_item id (the root category's item_id)."""
    tree = client.get_gradebook_tree(course_id)  # type: ignore[call-arg]
    return int(tree["root"]["item_id"])


def _resolve_parent_cat_id(
        ch: Change,
        created_cats_by_tag: dict[str, int],
) -> int:
    """Return ch.target_parent_cat_id or, if 0, resolve via pending_parent_tag."""
    if ch.target_parent_cat_id:
        return ch.target_parent_cat_id
    if ch.parent_cat_id:
        return ch.parent_cat_id
    if ch.pending_parent_tag and ch.pending_parent_tag in created_cats_by_tag:
        return created_cats_by_tag[ch.pending_parent_tag]
    return 0


def _apply_one(
        client: MoodleClientProtocol,
        course_id: CourseId,
        ch: Change,
        created_cats: dict[str, int],
        created_cats_by_tag: dict[str, int],
        created_items: dict[str, int],
) -> None:
    from moodlectl.types import GradeCategoryId as _Cid, GradeItemId as _Iid

    if ch.kind == CREATE_CATEGORY:
        name = ch.payload.get("fullname", "")
        # Resolve parent: it might be an existing cat (parent_cat_id) OR a
        # category being created earlier in this same push (pending_parent_tag).
        parent_cat = ch.parent_cat_id or created_cats_by_tag.get(ch.pending_parent_tag, 0)
        if not parent_cat:
            raise RuntimeError(
                f"CREATE_CATEGORY {name!r}: parent not resolved "
                f"(tag={ch.pending_parent_tag!r}). Create the parent first."
            )
        new_id = client.save_grade_category(
            course_id, _Cid(0), dict(ch.payload), parent_cat_id=_Cid(parent_cat),
        )
        created_cats[name] = int(new_id)
        if ch.own_tag:
            created_cats_by_tag[ch.own_tag] = int(new_id)
        # Moodle's create-category sometimes lands the new cat at root rather
        # than under the requested parent — if so, move it into place.
        try:
            tree = client.get_gradebook_tree(course_id)  # type: ignore[call-arg]
            def _find(cat):
                if cat["cat_id"] == int(new_id):
                    return cat
                for s in cat["subcategories"]:
                    r = _find(s)
                    if r:
                        return r
                return None
            placed = _find(tree["root"])
            if placed is not None and int(placed.get("parent_cat_id") or 0) != parent_cat:
                client.move_grade_item(  # type: ignore[call-arg]
                    course_id, item_eid=f"cg{int(new_id)}",
                    target_eid=f"cg{parent_cat}", first=True,
                )
        except Exception:
            pass
        return

    if ch.kind == UPDATE_CATEGORY:
        client.save_grade_category(course_id, _Cid(ch.target_cat_id), dict(ch.payload))
        return

    if ch.kind == CREATE_ITEM:
        if not ch.payload:
            # SKIP marker (activity-backed item that we can't create here).
            return
        name = ch.payload.get("itemname", "")
        parent_cat = ch.parent_cat_id or created_cats_by_tag.get(ch.pending_parent_tag, 0)
        if not parent_cat:
            raise RuntimeError(
                f"CREATE_ITEM {name!r}: parent not resolved "
                f"(tag={ch.pending_parent_tag!r})."
            )
        new_id = client.save_grade_item(
            course_id, _Iid(0), dict(ch.payload), parent_cat_id=_Cid(parent_cat),
        )
        created_items[name] = int(new_id)
        # If the YAML node has a calculation, push it now (we just got the id).
        yaml_calc = (ch.yaml_node.get("calculation") or "").strip()
        if yaml_calc:
            client.save_grade_calculation(course_id, new_id, yaml_calc)
        return

    if ch.kind == UPDATE_ITEM:
        if ch.via_calc_form:
            # idnumber update on activity-backed item — route through the
            # course-total calc form's idnumbers[] override.
            idnumber = ch.payload.get("idnumber", "")
            if ch.course_total_item_id == 0:
                raise RuntimeError("via_calc_form requires course_total_item_id to be set")
            current_formula, _ = client.get_grade_calculation(  # type: ignore[call-arg]
                course_id, _Iid(ch.course_total_item_id),
            )
            client.save_grade_calculation(
                course_id, _Iid(ch.course_total_item_id), current_formula,
                idnumber_overrides={_Iid(ch.target_item_id): idnumber},
            )
            return
        client.save_grade_item(course_id, _Iid(ch.target_item_id), dict(ch.payload))
        return

    if ch.kind == MOVE_ITEM:
        target_parent_cat = ch.target_parent_cat_id or created_cats_by_tag.get(ch.pending_parent_tag, 0)
        if not target_parent_cat:
            raise RuntimeError(
                f"MOVE_ITEM {ch.target_eid}: target parent not resolved "
                f"(tag={ch.pending_parent_tag!r})."
            )
        client.move_grade_item(
            course_id,
            item_eid=ch.target_eid,
            target_eid=f"cg{target_parent_cat}",
            first=True,
        )
        return

    if ch.kind == SET_MODULE_VISIBLE:
        cmid = int(ch.payload.get("cmid") or 0)
        if not cmid:
            raise RuntimeError(f"SET_MODULE_VISIBLE {ch.target_eid}: no cmid in payload")
        from moodlectl.types import Cmid as _Cmid
        client.set_module_visible(_Cmid(cmid), visible=(ch.payload.get("visible") == "1"))
        return

    if ch.kind == SET_CALCULATION:
        client.save_grade_calculation(
            course_id, _Iid(ch.target_item_id), ch.formula,
            idnumber_overrides=({_Iid(k): v for k, v in ch.idnumber_overrides.items()} if ch.idnumber_overrides else None),
        )
        return

    if ch.kind == DELETE_ITEM:
        # DELETE_ITEM handles activity-backed items only — calls delete_module
        # on the underlying cmid. Manual items can't be deleted via web (Moodle
        # JS-only modal); diff refuses to emit DELETE_ITEM for them.
        if ch.target_item_id == 0 or not ch.payload.get("cmid"):
            raise RuntimeError(
                f"DELETE_ITEM {ch.target_eid}: no cmid available — cannot delete "
                "(manual items must be deleted via the Moodle UI)."
            )
        from moodlectl.types import Cmid as _Cmid
        client.delete_module(_Cmid(int(ch.payload["cmid"])))  # type: ignore[arg-type]
        return

    raise RuntimeError(f"Unknown change kind: {ch.kind}")


def render_diff(changes: list[Change]) -> str:
    """Human-readable summary of a Change list (for --dry-run / push preview)."""
    if not changes:
        return "(no changes)"
    by_kind: dict[str, list[Change]] = {}
    for c in changes:
        by_kind.setdefault(c.kind, []).append(c)
    lines: list[str] = []
    for kind in [CREATE_CATEGORY, CREATE_ITEM, MOVE_ITEM, UPDATE_CATEGORY, UPDATE_ITEM,
                 SET_MODULE_VISIBLE, SET_CALCULATION, DELETE_ITEM]:
        items = by_kind.get(kind, [])
        if not items:
            continue
        lines.append(f"{kind} ({len(items)}):")
        for c in items:
            lines.append(f"  • {c.label}")
    return "\n".join(lines)
